version: '3.0'

services:

  for_chatgpt:
    build: ../ # using layer cache
    container_name: node-chatgpt
    working_dir: /app
    volumes:
      - ../../:/app:cached
      #      - - ../supervisor.conf:/etc/supervisor/conf.d/node_comic.conf:cached # 暂时用不上，目前只会挂载 www 服务
      - ../ini.sh:/usr/src/ini.sh:cached
      - /tmp/node_chatgpt:/tmp/node_chatgpt:cached
    ports:
      - 3995:4040
    environment:
      TZ: Asia/Shanghai
      NODE_ENV: production
      TERM: xterm
      NODE_OPTIONS : --openssl-legacy-provider

    networks:
      default:
        ipv4_address: 172.20.0.162
    # 生产开启这个
    command: bash -c "bash /usr/src/ini.sh "
#    command: bash -c "/usr/local/bin/node /app/dist/www --conf='/app/app.yaml'"
    # 部署资源限制
    deploy:
      replicas: 1  # 指定部署数量
      resources:
        limits: # cpu最大使用数
          cpus: '1.5' # 该服务cpu资源可用百分比，单个cpu打满就是 100%, 这里的 1.0 就是 100% 的 意思
          memory: 1000M # 主要是编译耗内存：特别是www服务的编译 峰值700~800M，如果只编译 task服务 只需要200M 就够用

networks:
  default:
    external:
      name: network_open_ai
